// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddMedicamentController from "./add_medicament_controller"
application.register("add-medicament", AddMedicamentController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import FlatpickrRangeController from "./flatpickr_range_controller"
application.register("flatpickr-range", FlatpickrRangeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SubmitLinkController from "./submit_link_controller"
application.register("submit-link", SubmitLinkController)
